package com.edu.less17.institute.controller;

public enum CommandName {
	SAVECOURSE, REMOVECOURSEBYID, GETCOURSES, CONDUCTLESSON, GETSTUDENTSBYALPHABET, GETSTUDENTSBYAVERAGEGRADE,
	GETCOURSEBYID, ADDSTUDENT

}
